/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    id("com.github.johnrengelman.shadow") version "8.1.1" // Maven Shade Plugin 대체용
}

group = "com.rrayy"
version = "2.0.0"
description = "A little Minecraft Paper Trade Plugin"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/") // Paper API
    maven("https://oss.sonatype.org/content/repositories/snapshots/") // BungeeCord Chat API
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.7-R0.1-SNAPSHOT") // Paper API
    implementation('net.kyori:adventure-api:4.14.0')
    implementation("net.kyori:adventure-text-serializer-legacy:4.12.0")
}

tasks {
    processResources {
        filteringCharset = "UTF-8"
        filesMatching("**/*.yml") {
            expand(project.properties)
        }
    }

    compileJava {
        options.encoding = "UTF-8"
        // Java 21에 맞춰 source/target compatibility도 명시적으로 지정
        sourceCompatibility = JavaVersion.VERSION_21.toString()
        targetCompatibility = JavaVersion.VERSION_21.toString()
    }

    shadowJar {
        archiveClassifier.set("")
        minimize() // 불필요한 의존성 제거
    }

    build {
        dependsOn(shadowJar)
    }
}