name: TradePlugin
version: '${project.version}'
main: com.rrayy.tradeplugin.main.Main
api-version: '1.21'
description: A little Minecraft Paper Trade Plugin
author: Robby3St
# website: https://https://github.com/Robby3St/TradePlugin/
commands:
  trade:
      description: Lets you trade with another person
      usage: /trade <Name> | /trade accept | /trade accept <Name> | /trade cancel | /trade deny | /trade deny <Name> | /trade author | /trade version | /trade download | /trade toggle | /trade block | /trade block <Players separated by ","> | /trade unblock | /trade unblock <Players separated by ",">
